version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_auth_api
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN:-3600}
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?authSource=admin
      - MONGODB_DATABASE=${MONGODB_DATABASE:-Users}
      - REDIS_URI=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB:-0}
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - auth_api_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-Users}
    networks:
      - auth_api_network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - auth_api_network

networks:
  auth_api_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
